name: onetep docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs-build:
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx-latexpdf:5.3.0
    steps:
    - uses: actions/checkout@v4
    - name: sphinx
      run: |
        pip install sphinx-rtd-dark-mode
        make latexpdf
        cp _build/latex/ONETEP_Documentation.pdf  _static/
        make html

  docs-deploy:
    if: github.ref_name == 'main'  && github.repository == 'onetep-devel/documentation'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx-latexpdf:5.3.0

    steps:
    - uses: actions/checkout@v4
    - name: sphinx
      run: |
        pip install sphinx-rtd-dark-mode
        make latexpdf
        cp _build/latex/ONETEP_Documentation.pdf  _static/
        make html
    - name: upload
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './_build/html/.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

