name: onetep docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx:5.3.0

    steps:
    - uses: actions/checkout@v3
    - name: sphinx
      run: |
        cd doc
        make html
        make latexpdf
    - name: archive
      uses: actions/upload-artifact@v3
      with:
        name: sphinx-doc
        path: [doc/_build/html,doc/_build/latex/ONETEP_Documentation.pdf]
        retention-days: 5

